### ISSUE TITLE
#feature: 💎 Cryptocurrency.

### ISSUE THREAD

**Issue by felixyeahh** [Baffuu/jivopolis-alt#4]
- a thing whose value will change randomly every few hours. There will be 4 types of it - 💎fyCoin, 🧿Mithereum, 🧬Gather, 🪙 Recegon 
- changes in values: once every 4 hours, from -500 to +650 (for some value changes more, for others - less), the value cannot fall below $5. which currency will eventually become the most expensive - the will of the random house, not the admins or anything else.
- in changing the value, I also propose introducing the sale and purchase of the cryptocurrency itself. Those, if it is bought - the value grows more strongly, if it is sold - it falls more strongly.
- It will be possible to buy and sell cryptocurrency on the 📊Exchange. It will be located ... and later as an app inside a phone.

### Achievements:
 - 📉 Broker Beginner - buy any cryptocurrency.
 - 📈 Stonks - sell any cryptocurrency

### 🪼 Tasks:
- [x]  💎 cryptocurrency as an item
- [ ]  💳 special wallet
- [ ]  📊 exchange center 
- [x]  📈 value change
- [ ]  📉 additional parameters of change
- [ ] 🏆 achievements
- [x] 🔻🔼 Show how the currency changed
